version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production2
        DB_URL: 'mongodb+srv://ragedrage:ig957301@cluster0.xbef61b.mongodb.net/decorspirit-shop'
        PORT: 8080
        SECRET_KEY: 'cucumberbl'
        MAIL_EXTRA_PASS: QVckrZiG75jwhK1TGYK
    ports:
      - 8080:8080
